- name: check pt-query-digest installed
  command: which pt-query-digest
  register: pt_installed
  ignore_errors: true
  tags:
    - install
    - never

- include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: pt_installed is failed
  tags:
    - install
    - never
