- name: install utilities
  apt:
    name: "{{ item }}"
  with_items:
    - git
    - htop
    - jq
    - rsync
    - tig

- name: deploy utility files
  become: false
  copy:
    src: "{{ item }}"
    dest: ./
    force: false
  with_items:
    - Makefile
