- include_tasks: "{{ ansible_os_family | lower }}.yml"
  tags:
    - install
    - never

- become: false
  copy:
    src: .config/git
    dest: ~/.config/
    force: false
  tags:
    - install
    - never
