- include_tasks:
    file: "{{ ansible_os_family | lower }}.yml"
    apply:
      tags:
        - install
        - never
  tags:
    - install
    - never

- become: false
  copy:
    src: .config/git
    dest: ~/.config/
    force: false
  tags:
    - install
    - never
