- name: install alp for {{ arch[ansible_architecture] }}
  unarchive:
    src: "{{ download_url }}/{{ version }}/alp_linux_{{ arch[ansible_architecture] }}.tar.gz"
    dest: /usr/local/bin
    creates: /usr/local/bin/alp
    remote_src: true
    mode: 0755
  tags:
    - install
    - never

- name: deploy alp.yml
  become: false
  copy:
    src: alp.yml
    dest: ./
    force: false
  tags:
    - install
    - never
