- name: check mysqldef installed
  command: which mysqldef
  register: mysqldef_installed
  ignore_errors: true

- name: install mysqldef
  when: mysqldef_installed is failed
  block:
    - name: check system architecture
      command: uname -m
      register: architecture

    - name: install mysqldef(x86_64)
      when: architecture.stdout == "x86_64"
      unarchive: &mysqldef
        src: "{{ download_url }}/{{ version }}/mysqldef_linux_amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        mode: 0755

    - name: install mysqldef(arm64)
      when: architecture.stdout == "arm64"
      unarchive:
        <<: *mysqldef
        src: "{{ download_url }}/{{ version }}/mysqldef_linux_arm64.tar.gz"
