- hosts: init
  become: true
  roles:
    - install/alp
    - install/git
    - install/htop
    - install/mysqldef
    - install/percona-toolkit
    - install/tig
    - install/valkey
    - setting/disable-apparmor
    - setting/disable-selinux
    - deploy/repo

- hosts: webapp
  become: true
  roles:
    - deploy/nginx

- hosts: db
  become: true
  roles:
    - deploy/mysql
