- hosts: all
  become: true
  roles:
    - install/alp
    - install/git
    - install/htop
    - install/mysqldef
    - install/percona-toolkit
    - install/tig
    - setting/disable-apparmor
    - setting/disable-selinux
    - deploy/repo
